### ISSUE TITLE
Follow Laravel route files naming convention

### ISSUE THREAD

**Issue by bilogic** [Jeroen-G/packager-skeleton#14]
Does it make sense to change and expand this line in the ServiceProvider from

https://github.com/Jeroen-G/packager-skeleton/blob/6e8c8412df2224191baa4451d27631277f0c4e43/src/MyPackageServiceProvider.php#L19

To

```
// $this->loadRoutesFrom(__DIR__.'/routes.php'); // packager
// $this->loadRoutesFrom(__DIR__.'/../routes/web.php'); // Laravel convention
// $this->loadRoutesFrom(__DIR__.'/../routes/api.php'); // Laravel convention
// $this->loadRoutesFrom(__DIR__.'/../routes/console.php'); // Laravel convention
```

**Comment by Jeroen-G** [comment]
Not really, it really is there to give you a quick head start, and not every time you need all those files.

**Comment by Jeroen-G** [comment]
Thanks for thinking along anyway!
