### ISSUE TITLE
Omit requiring illuminate/support

### ISSUE THREAD

**Issue by bilogic** [Jeroen-G/packager-skeleton#17]
Hi,

I was thinking, is it necessary to require `illuminate/support` in `composer.json`?

1. This started because my project is still relying on version 8
2. As this skeleton is meant to create Laravel packages, I think it is safe to assume the parent project already includes the "correct" version of `illuminate/support`
3. If the new package is installed in non-Laravel projects, I suspect `illuminate/support` is still not enough
4. My view is to remove since it doesn't help that much and in fact, becomes a line that requires constant maintenance

Thank you.

**Comment by Jeroen-G** [comment]
Your package may not be working in Laravel 10, the illuminate requirement allows you to set the versions of Laravel that you have (or want to be) tested. Of course you may remove /change it entirely if you want to! I however am keeping it in the skeleton.

**Comment by bilogic** [comment]
ok thanks
