### ISSUE TITLE
Publish group names

### ISSUE THREAD

**Issue by TerrePorter** [Jeroen-G/packager-skeleton#2]
Its more of a question as to why verses it being a issue/bug.

I'm curious as to why you prepend the package name to the publish group.

```
// Publishing the configuration file.
$this->publishes([
      __DIR__.'/../config/:lc:package.php' => config_path(':lc:package.php'),
], ':lc:package.config');
```

Why not just use "config" as the group? Then in the publish command its '--tag="config"' verses  '--tag="mypackage.config"

I am already specifying the package in the publish command.

I know i can just easily change it, but i'm curious as to the reason behind the naming convention.

**Comment by Jeroen-G** [comment]
> I am already specifying the package in the publish command.

Not necessarily!

```bash
php artisan vendor:install --tag=packager.config
```

Publishes only Packager's config, whereas with just a `config` tag you would need to type this:

```bash
php artisan vendor:install --provider=JeroenG/LaravelPackager/LaravelPackagerServiceProvider --tag=config
```

Or use

```bash
php artisan vendor:install --tag=config
```

But then you risk publishing files for packages you don't want to but that have the same tag.

**Comment by TerrePorter** [comment]
Ahh, I see this can be very useful. Thanks for the great explanation.
